["!local"]
rockTexture = "minecraft:block/stone"

[":amethyst_ore"]
oreTexture = ":blocks/amethyst_ore"

[":copper_ore"]
oreTexture = ":blocks/copper_ore"
useGetDrops = true

[":malachite_ore"]
oreTexture = ":blocks/malachite_ore"

[":ruby_ore"]
oreTexture = ":blocks/ruby_ore"

[":sapphire_ore"]
oreTexture = ":blocks/sapphire_ore"

[":silver_ore"]
oreTexture = ":blocks/silver_ore"
useGetDrops = true

[":teslatite_ore"]
oreTexture = ":blocks/teslatite_ore"

[":tungsten_ore"]
oreTexture = ":blocks/tungsten_ore"
useGetDrops = true

[":zinc_ore"]
oreTexture = ":blocks/zinc_ore"
useGetDrops = true

