["!local"]
rockTexture="minecraft:block/stone"
maxOreLayerColorDiff=65

[":bat_ore"]
oreTexture=":blocks/bat_ore"

[":blaze_ore"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/blaze_ore"
maxOreLayerColorDiff=50

[":chicken_ore"]
oreTexture=":blocks/chicken_ore"

[":cod_ore"]
oreTexture=":blocks/cod_ore"

[":cow_ore"]
oreTexture=":blocks/cow_ore"

[":creeper_ore"]
oreTexture=":blocks/creeper_ore"

[":enderman_ore"]
oreTexture=":blocks/enderman_ore"

[":ghast_ore"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/ghast_ore"
maxOreLayerColorDiff=50

[":guardian_ore"]
oreTexture=":blocks/guardian_ore"

[":magma_cube_ore"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/magma_cube_ore"
maxOreLayerColorDiff=50

[":phantom_ore"]
oreTexture=":blocks/phantom_ore"

[":pig_ore"]
oreTexture=":blocks/pig_ore"

[":pufferfish_ore"]
oreTexture=":blocks/pufferfish_ore"

[":rabbit_ore"]
oreTexture=":blocks/rabbit_ore"

[":salmon_ore"]
oreTexture=":blocks/salmon_ore"

[":sheep_ore"]
oreTexture=":blocks/sheep_ore"

[":skeleton_ore"]
oreTexture=":blocks/skeleton_ore"

[":slime_ore"]
oreTexture=":blocks/slime_ore"

[":spider_ore"]
oreTexture=":blocks/spider_ore"

[":squid_ore"]
oreTexture=":blocks/squid_ore"

[":witch_ore"]
oreTexture=":blocks/witch_ore"

[":wither_skeleton_ore"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/wither_skeleton_ore"
maxOreLayerColorDiff=50

[":zombie_ore"]
oreTexture=":blocks/zombie_ore"

[":zombie_pigman_ore"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/zombie_pigman_ore"
maxOreLayerColorDiff=50

