["!local"]
rockTexture=":block/gaia_stone"

[":cinnabar_ore"]
oreTexture=":block/cinnabar_ore"

[":hematite_ore"]
oreTexture=":block/hematite_ore"
maxOreLayerColorDiff=30

[":labradorite_ore"]
oreTexture=":block/labradorite_ore"

[":moonstone_ore"]
oreTexture=":block/moonstone_ore"

[":opal_ore_blue"]
oreTexture=":block/opal_ore_blue"

[":opal_ore_green"]
oreTexture=":block/opal_ore_green"

[":opal_ore_red"]
oreTexture=":block/opal_ore_red"

[":opal_ore_white"]
oreTexture=":block/opal_ore_white"

[":pyrite_ore"]
oreTexture=":block/pyrite_ore"

[":sugilite_ore"]
oreTexture=":block/sugilite_ore"

