["!local"]
rockTexture="minecraft:block/stone"

[":gobber2_ore"]
oreTexture=":block/gobber2_ore"

[":gobber2_ore_end"]
rockTexture="minecraft:block/end_stone"
oreTexture=":block/gobber2_ore_end"
lateGeneration=true

[":gobber2_ore_nether"]
rockTexture="minecraft:block/netherrack"
oreTexture=":block/gobber2_ore_nether"
maxOreLayerColorDiff=20

[":gobber2_lucky_block"]
oreTexture=":block/gobber2_lucky_block"

