["!local"]
rockTexture="minecraft:block/stone"

[":aluminum_ore"]
oreTexture=":block/aluminum_ore"

[":bismuth_ore"]
oreTexture=":block/bismuth_ore"

[":copper_ore"]
oreTexture=":block/copper_ore"

[":iridium_ore"]
oreTexture=":block/iridium_ore"

[":lead_ore"]
oreTexture=":block/lead_ore"

[":nickel_ore"]
oreTexture=":block/nickel_ore"

[":platinum_ore"]
oreTexture=":block/platinum_ore"

[":silver_ore"]
oreTexture=":block/silver_ore"

[":tin_ore"]
oreTexture=":block/tin_ore"

[":uranium_ore"]
oreTexture=":block/uranium_ore"

[":zinc_ore"]
oreTexture=":block/zinc_ore"

