["!local"]
rockTexture = ":blocks/nightstone"

[":archaic_ore"]
rockTexture = ":blocks/trenchstone"
oreTexture = ":blocks/archaic_ore"

[":dark_pearl_ore"]
oreTexture = ":blocks/dark_pearl_ore"
maxOreLayerColorDiff = 10

[":ebonite_ore"]
oreTexture = ":blocks/ebonite_ore"

[":nagrilite_ore"]
oreTexture = ":blocks/nagrilite_ore"
maxOreLayerColorDiff = 15

[":tenebrum_ore"]
oreTexture = ":blocks/tenebrum_ore"
maxOreLayerColorDiff = 15

