["!local"]
rockTexture="minecraft:block/netherrack"

[":argonite_ore"]
oreTexture=":block/argonite_ore"

[":ashstone_ore"]
oreTexture=":block/ashstone_ore"

[":dragonstone_ore"]
oreTexture=":block/dragonstone_ore"

[":fyrite_ore"]
oreTexture=":block/fyrite_ore"

[":illumenite_ore"]
rockTexture="minecraft:block/glowstone"
oreTexture=":block/illumenite_ore"
lateGeneration=true

[":malachite_ore"]
oreTexture=":block/malachite_ore"

