["!local"]
rockTexture = "minecraft:block/stone"

[":amethyst_ore"]
oreTexture = ":block/amethyst_ore"

[":black_opal_ore"]
oreTexture = ":block/black_opal_ore"
maxOreLayerColorDiff=30

[":end_amethyst_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/end_amethyst_ore"

[":end_black_opal_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/end_black_opal_ore"

[":nether_amethyst_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/nether_amethyst_ore"

[":nether_black_opal_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/nether_black_opal_ore"

