[":dimensionalshard_end"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ores/dimensionalshard_end"

[":dimensionalshard_nether"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ores/dimensionalshard_nether"
maxOreLayerColorDiff = 100

[":dimensionalshard_overworld"]
rockTexture = "minecraft:block/stone"
oreTexture = ":block/ores/dimensionalshard_overworld"
maxOreLayerColorDiff = 100

