["!local"]
rockTexture = "minecraft:block/stone"

[":agate_ore"]
oreTexture = ":block/ore/gem/agate"

[":alexandrite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/alexandrite"

[":amber_ore"]
oreTexture = ":block/ore/gem/amber"

[":amethyst_ore"]
oreTexture = ":block/ore/gem/amethyst"

[":ametrine_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/ametrine"

[":ammolite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/ammolite"

[":apatite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/apatite"

[":aquamarine_ore"]
oreTexture = ":block/ore/gem/aquamarine"

[":benitoite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/benitoite"

[":black_diamond_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/black_diamond"

[":carnelian_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/carnelian"

[":cats_eye_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/cats_eye"

[":chaos_ore"]
oreTexture = ":block/ore/chaos_ore"

[":chrysoprase_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/chrysoprase"

[":citrine_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/citrine"

[":coral_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/coral"

[":ender_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/ender_ore"

[":euclase_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/euclase"

[":fluorite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/fluorite"

[":garnet_ore"]
oreTexture = ":block/ore/gem/garnet"

[":green_sapphire_ore"]
oreTexture = ":block/ore/gem/green_sapphire"

[":heliodor_ore"]
oreTexture = ":block/ore/gem/heliodor"

[":iolite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/iolite"

[":jade_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/jade"

[":jasper_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/jasper"

[":kunzite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/kunzite"

[":kyanite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/kyanite"

[":lepidolite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/lepidolite"

[":malachite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/malachite"

[":moldavite_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/moldavite"

[":moonstone_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/moonstone"

[":morganite_ore"]
oreTexture = ":block/ore/gem/morganite"

[":multi_ore_classic"]
oreTexture = ":block/ore/multi_classic"

[":multi_ore_dark"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/multi_dark"

[":multi_ore_light"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/multi_light"

[":onyx_ore"]
oreTexture = ":block/ore/gem/onyx"

[":opal_ore"]
oreTexture = ":block/ore/gem/opal"

[":pearl_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/pearl"

[":peridot_ore"]
oreTexture = ":block/ore/gem/peridot"

[":phosphophyllite_ore"]
oreTexture = ":block/ore/gem/phosphophyllite"

[":pyrope_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/pyrope"

[":rose_quartz_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/rose_quartz"

[":ruby_ore"]
oreTexture = ":block/ore/gem/ruby"

[":sapphire_ore"]
oreTexture = ":block/ore/gem/sapphire"

[":silver_ore"]
oreTexture = ":block/silver_ore"

[":sodalite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/sodalite"

[":spinel_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/spinel"

[":sunstone_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/sunstone"

[":tanzanite_ore"]
oreTexture = ":block/ore/gem/tanzanite"

[":tektite_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/tektite"

[":topaz_ore"]
oreTexture = ":block/ore/gem/topaz"

[":turquoise_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/turquoise"

[":yellow_diamond_ore"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/ore/gem/yellow_diamond"

[":zircon_ore"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/ore/gem/zircon"

