["!local"]
rockTexture = "minecraft:block/end_stone"
lateGeneration = true

[":end_ore_coal"]
oreTexture = ":blocks/end_ore_coal"

[":end_ore_diamond"]
oreTexture = ":blocks/end_ore_diamond"

[":end_ore_emerald"]
oreTexture = ":blocks/end_ore_emerald"

[":end_ore_gold"]
oreTexture = ":blocks/end_ore_gold"

[":end_ore_iron"]
oreTexture = ":blocks/end_ore_iron"
maxOreLayerColorDiff=40

[":end_ore_lapis"]
oreTexture = ":blocks/end_ore_lapis"

[":end_ore_redstone"]
oreTexture = ":blocks/end_ore_redstone"

[":nether_ore_coal"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_coal"

[":nether_ore_diamond"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_diamond"

[":nether_ore_emerald"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_emerald"

[":nether_ore_gold"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_gold"

[":nether_ore_iron"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_iron"

[":nether_ore_lapis"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_lapis"

[":nether_ore_redstone"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":blocks/nether_ore_redstone"

