["!local"]
rockTexture="minecraft:block/stone"

[":amethyst_ore"]
oreTexture=":block/amethyst_ore"

[":quartz_ore"]
oreTexture=":block/quartz_ore"

[":ruby_ore"]
oreTexture=":block/ruby_ore"

[":sapphire_ore"]
oreTexture=":block/sapphire_ore"

[":topaz_ore"]
oreTexture=":block/topaz_ore"

