["!local"]
rockTexture = ":block/stone"

[":coal_ore"]
oreTexture = ":block/coal_ore"

[":iron_ore"]
oreTexture = ":block/iron_ore"

[":gold_ore"]
oreTexture = ":block/gold_ore"

[":redstone_ore"]
oreTexture = ":block/redstone_ore"

[":diamond_ore"]
oreTexture = ":block/diamond_ore"

[":lapis_ore"]
oreTexture = ":block/lapis_ore"

[":emerald_ore"]
oreTexture = ":block/emerald_ore"

[":copper_ore"]
oreTexture = ":block/copper_ore"

[":deepslate_coal_ore"]
oreTexture = ":block/deepslate_coal_ore"
rockTexture = ":block/deepslate"

[":deepslate_iron_ore"]
oreTexture = ":block/deepslate_iron_ore"
rockTexture = ":block/deepslate"

[":deepslate_gold_ore"]
oreTexture = ":block/deepslate_gold_ore"
rockTexture = ":block/deepslate"

[":deepslate_redstone_ore"]
oreTexture = ":block/deepslate_redstone_ore"
rockTexture = ":block/deepslate"

[":deepslate_diamond_ore"]
oreTexture = ":block/deepslate_diamond_ore"
rockTexture = ":block/deepslate"

[":deepslate_lapis_ore"]
oreTexture = ":block/deepslate_lapis_ore"
rockTexture = ":block/deepslate"

[":deepslate_emerald_ore"]
oreTexture = ":block/deepslate_emerald_ore"
rockTexture = ":block/deepslate"

[":deepslate_copper_ore"]
oreTexture = ":block/deepslate_copper_ore"
rockTexture = ":block/deepslate"

[":nether_quartz_ore"]
oreTexture = ":block/nether_quartz_ore"
rockTexture = ":block/netherrack"

[":nether_gold_ore"]
oreTexture = ":block/nether_gold_ore"
rockTexture = ":block/netherrack"
