["!local"]
useGetDrops=true

[":dye_ore"]
rockTexture="minecraft:block/stone"
oreTexture=":blocks/dye_ore"
maxOreLayerColorDiff=5

[":dye_ore_end"]
rockTexture="minecraft:block/end_stone"
oreTexture=":blocks/dye_ore_end"
maxOreLayerColorDiff=5

[":dye_ore_nether"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/dye_ore_nether"
maxOreLayerColorDiff=5

[":ender_pearl_ore"]
rockTexture="minecraft:block/stone"
oreTexture=":blocks/ender_pearl_ore"

[":ender_pearl_ore_end"]
rockTexture="minecraft:block/end_stone"
oreTexture=":blocks/ender_pearl_ore_end"

[":ender_pearl_ore_nether"]
rockTexture="minecraft:block/netherrack"
oreTexture=":blocks/ender_pearl_ore_nether"

