["!local"]
lateGeneration = true

[":super_useless_ore"]
rockTexture = "minecraft:block/stone"
oreTexture = ":block/super_useless_ore"
lateGeneration = false

[":super_useless_ore_end"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/super_useless_ore_end"

[":super_useless_ore_nether"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/super_useless_ore_nether"

[":useless_ore"]
rockTexture = "minecraft:block/stone"
oreTexture = ":block/useless_ore"
lateGeneration = false

[":useless_ore_end"]
rockTexture = "minecraft:block/end_stone"
oreTexture = ":block/useless_ore_end"

[":useless_ore_nether"]
rockTexture = "minecraft:block/netherrack"
oreTexture = ":block/useless_ore_nether"

