[":netheraluminum_ore"]

[":nethercoal_ore"]

[":nethercopper_ore"]

[":netherdiamond_ore"]

[":netheremerald_ore"]

[":nethergold_ore"]

[":netheriron_ore"]

[":netherlapis_ore"]

[":netherlead_ore"]

[":nethernickel_ore"]

[":netherredstone_ore"]

[":nethersilver_ore"]

[":nethertin_ore"]

[":netheruranium_ore"]

