[":end_ore_coal"]

[":end_ore_diamond"]

[":end_ore_emerald"]

[":end_ore_gold"]

[":end_ore_iron"]

[":end_ore_lapis"]

[":end_ore_redstone"]

[":nether_ore_coal"]

[":nether_ore_diamond"]

[":nether_ore_emerald"]

[":nether_ore_gold"]

[":nether_ore_iron"]

[":nether_ore_lapis"]

[":nether_ore_redstone"]

