[":bat_ore"]

[":blaze_ore"]

[":chicken_ore"]

[":cod_ore"]

[":cow_ore"]

[":creeper_ore"]

[":enderman_ore"]

[":ghast_ore"]

[":guardian_ore"]

[":magma_cube_ore"]

[":phantom_ore"]

[":pig_ore"]

[":pufferfish_ore"]

[":rabbit_ore"]

[":salmon_ore"]

[":sheep_ore"]

[":skeleton_ore"]

[":slime_ore"]

[":spider_ore"]

[":squid_ore"]

[":witch_ore"]

[":wither_skeleton_ore"]

[":zombie_ore"]

[":zombie_pigman_ore"]

