[":netheroreagate"]

[":netheroreamethyst"]

[":netherorechrysocolla"]

[":netherorecitrine"]

[":netheroregarnet"]

[":netherorejade"]

[":netherorejasper"]

[":netheroremalachite"]

[":netheroreonyx"]

[":netherorephoenixite"]

[":netheroreruby"]

[":netheroresapphire"]

[":netherorespinel"]

[":netheroresugilite"]

[":netheroretopaz"]

[":netheroretourmaline"]

[":oreagate"]

[":oreamethyst"]

[":orechrysocolla"]

[":orecitrine"]

[":oregarnet"]

[":orejade"]

[":orejasper"]

[":oremalachite"]

[":oreonyx"]

[":orephoenixite"]

[":oreruby"]

[":oresapphire"]

[":orespinel"]

[":oresugilite"]

[":oretopaz"]

[":oretourmaline"]

