[":agate_ore"]

[":alexandrite_ore"]

[":amber_ore"]

[":amethyst_ore"]

[":ametrine_ore"]

[":ammolite_ore"]

[":apatite_ore"]

[":aquamarine_ore"]

[":benitoite_ore"]

[":black_diamond_ore"]

[":carnelian_ore"]

[":cats_eye_ore"]

[":chaos_ore"]

[":chrysoprase_ore"]

[":citrine_ore"]

[":coral_ore"]

[":ender_ore"]

[":euclase_ore"]

[":fluorite_ore"]

[":garnet_ore"]

[":green_sapphire_ore"]

[":heliodor_ore"]

[":iolite_ore"]

[":jade_ore"]

[":jasper_ore"]

[":kunzite_ore"]

[":kyanite_ore"]

[":lepidolite_ore"]

[":malachite_ore"]

[":moldavite_ore"]

[":moonstone_ore"]

[":morganite_ore"]

[":multi_ore_classic"]

[":multi_ore_dark"]

[":multi_ore_light"]

[":onyx_ore"]

[":opal_ore"]

[":pearl_ore"]

[":peridot_ore"]

[":phosphophyllite_ore"]

[":pyrope_ore"]

[":rose_quartz_ore"]

[":ruby_ore"]

[":sapphire_ore"]

[":silver_ore"]

[":sodalite_ore"]

[":spinel_ore"]

[":sunstone_ore"]

[":tanzanite_ore"]

[":tektite_ore"]

[":topaz_ore"]

[":turquoise_ore"]

[":yellow_diamond_ore"]

[":zircon_ore"]

